### PR TITLE
Added ability to plot observability matrix

### PR DESCRIPTION
**Pull request by luisdavidgarcia**
Add two functions one for plotting observability and another for transformed version.

### CODE REVIEW

**Comment by kennedyengineering** [comment]
I like it. 

Problem is observability is in the theoretical discussion. We don't introduce the parameters until the next section. Is there a way to do this theoretically?

**Comment by kennedyengineering** [comment]
Or maybe keep things as they are, and just put in a new section in 'fitting model to visual data' at the end called 'state observability of optimal model parameters' or something...

**Comment by luisdavidgarcia** [comment]
Yeah I don't think we can plot a theoretical observability without some theoretical values. 

I do like you last point. We should these observability plots in the experimental sections instead of theoretical.

Also sounds like we could also show an example of what an observability ellipsoid is, but this seems more fitting in the background section.

**Comment by kennedyengineering** [comment]
Sweet, created the spot in the report. You just have to add the stuff. I'll look over the code more closely.

**Comment by kennedyengineering** [comment]
cleaned up, ready to merge when you're ready

**Pull request merged**
